version: '3'
services:
  jump:
    build: # build
      context: . # build context
      dockerfile: Dockerfile 
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - .:/home/jovyan
    command: start-notebook.sh --NotebookApp.token=''